
  
controllers:
  # left arm controller for dual robot
  joint_position_controller:
    type: joint_controller/JointPositionController
    joints:
      - left_thigh_joint
      - left_knee_joint
      - right_thigh_joint
      - right_knee_joint
    publish_rate: 10

  # joint state controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10