Kp: 0.1 #比例放大系数
Ki: 0.1 #积分放大系数
Kd: 0.1 #微分放大系数

eta: 0.5 #学习率
alpha: 0.05 #动量因子

##PID学习率
etaP: 0.15 
etaI: 0.15
etaD: 0.15

##中心矢量
c:
  -1.5
  -1
  -0.5
  0
  0.5
  1
  1.5
  -1.5
  -1
  -0.5
  0
  0.5
  1
  1.5
  -1.5
  -1
  -0.5
  0
  0.5
  1
  1.5
  -1.5
  -1
  -0.5
  0
  0.5
  1
  1.5


##函数宽度
b:
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1 
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1